// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Device.h"
#include <thrift/protocol/TJSONProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/THttpServer.h>

#include <dwfobj/Device.h>
#include <dwfobj/helper.h>
#include <dwfobj/easylogging++.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class DeviceHandler : virtual public DeviceIf {
 public:
  DeviceHandler() {
    // Your initialization goes here
  }

  void getDigitalInputConfig( ::DigitalInput& _return) {
    // Your implementation goes here
    printf("getDigitalInputConfig\n");
    _return.divider = getCRConfigInt(
            (dwf::ContinuousRangeConfiguration<int> *)
            &dev.digitalIn.divider);
    _return.bufferSize = getCRConfigInt(
            (dwf::ContinuousRangeConfiguration<int> *)
            &dev.digitalIn.bufferSize);
    _return.triggerPosition = getCRConfigInt(
            (dwf::ContinuousRangeConfiguration<int> *)
            &dev.digitalIn.triggerPosition);
    _return.internalClkFreq = dev.digitalIn.getInternalClkFreq();
    _return.__isset.internalClkFreq = true;
  }

  void configureDigitalInput( ::DigitalInput& _return, const  ::DigitalInput& config) {
    // Your implementation goes here
    printf("configureDigitalInput\n");
  }

  void resetDigitalInput() {
    // Your implementation goes here
    printf("resetDigitalInput\n");
    dev.digitalIn.reset();
  }

  void startDigitalInput() {
    // Your implementation goes here
    printf("startDigitalInput\n");
    dev.digitalIn.start();
  }

  void stopDigitalInput() {
    // Your implementation goes here
    printf("stopDigitalInput\n");
    dev.digitalIn.stop();
  }

  void readDigitalInput(std::vector< ::DigitalData> & _return) {
    // Your implementation goes here
    printf("readDigitalInput\n");
  }

  void getAnalogInputConfig( ::AnalogInput& _return) {
    // Your implementation goes here
    printf("getAnalogInputConfig\n");
  }

  void configureAnalogInput( ::AnalogInput& _return, const  ::AnalogInput& config) {
    // Your implementation goes here
    printf("configureAnalogInput\n");
  }

  void resetAnalogInput() {
    // Your implementation goes here
    printf("resetAnalogInput\n");
  }

  void startAnalogInput() {
    // Your implementation goes here
    printf("startAnalogInput\n");
  }

  void stopAnalogInput() {
    // Your implementation goes here
    printf("stopAnalogInput\n");
  }

  void readAnalogInput(std::vector< ::AnalogData> & _return) {
    // Your implementation goes here
    printf("readAnalogInput\n");
  }
 private:
  dwf::Device dev;
  ::CRConfigInt getCRConfigInt(dwf::ContinuousRangeConfiguration<int> * devCRConfig) {
      ::CRConfigInt returnVal;
      dwf::ContinuousRange<int> range = devCRConfig->getRange();
      printf("%s\n",range.toString().c_str());
      returnVal.val = devCRConfig->get();
      returnVal.min = range.min;
      returnVal.max = range.max;
      returnVal.__isset.min = true;
      returnVal.__isset.max = true;
      return returnVal;
  }

};

INITIALIZE_EASYLOGGINGPP

int main(int argc, char **argv) {
    initializeLogging(argc, argv);
    int port = 9090;
    shared_ptr<DeviceHandler> handler(new DeviceHandler());
    shared_ptr<TProcessor> processor(new DeviceProcessor(handler));
    shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
    shared_ptr<TTransportFactory> transportFactory(new THttpServerTransportFactory());
    shared_ptr<TProtocolFactory> protocolFactory(new TJSONProtocolFactory());

    TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
    server.serve();
    return 0;
}

